version: "3.6"

services:
  search-server:
    image: solr
    ports:
      - "8983:8983"
    deploy: 
      resources: 
        reservations:
          memory: 12g
      placement: 
        constraints:
          - node.labels.node_number==4
  # media-source:
  #   image: luongquocdat01091995/media-streaming-server:source
  search-client: 
    image: luongquocdat01091995/search-server:client
    environment: 
        - IP=131.155.35.54
    deploy: 
      placement: 
        constraints:
          - node.labels.node_number==4
  # media-client: 
  #   image: luongquocdat01091995/media-streaming-server:client
  #   environment: 
  #       - SERVER_IP=131.155.35.54
  # media-client: 
  #   image: luongquocdat01091995/media-streaming-server:client
  #   environment: 
  #       - SERVER_IP=131.155.35.54
  # media-client: 
  #   image: luongquocdat01091995/media-streaming-server:client
  #   environment: 
  #       - SERVER_IP=131.155.35.54