version: "3.6"

services:
  search-server:
    image: cloudsuite/web-search:server
    ports:
      - "8983:8983"
    deploy: 
      placement: 
        constraints:
          - node.labels.node_number==4
  # media-source:
  #   image: luongquocdat01091995/media-streaming-server:source
  search-client: 
    image: luongquocdat01091995/search-server:client
    environment: 
        - SERVER_IP=192.168.2.93
    deploy: 
      placement: 
        constraints:
          - node.labels.node_number==3
  # media-client: 
  #   image: luongquocdat01091995/media-streaming-server:client
  #   environment: 
  #       - SERVER_IP=131.155.35.54
  # media-client: 
  #   image: luongquocdat01091995/media-streaming-server:client
  #   environment: 
  #       - SERVER_IP=131.155.35.54
  # media-client: 
  #   image: luongquocdat01091995/media-streaming-server:client
  #   environment: 
  #       - SERVER_IP=131.155.35.54