version: "3.6"

services:
  search-client: 
    image: luongquocdat01091995/search-server:python_client
    environment: 
        - SERVER_IP=192.168.2.83
        - SERVER_PORT=8983
    restart: on-failure
    deploy: 
      placement: 
        constraints:
          - node.labels.node_number==4
  search-server:
    image: solr:8
    ports:
      - 8983:8983
    command: solr-demo
    deploy: 
      placement: 
        constraints:
          - node.labels.node_number==3